BASE_URL = 'https://www.virustotal.com/'

CATEGORY = {"Trojan": 0,
            "TrojSpy": 0,
            "TrojDownloader": 0,
            "Backdoor": 0,
            "Worm": 0,
            "Virus": 0,
            "Tool": 0,
            "Riskware": 0,
            "Adware": 0,
            "Ransomware": 0,
            "Exploit": 0,
            "PUA": 0
            }

AVEXCLUTIONLIST = ['Baidu-International',
                   'NANO-Antivirus',
                   'Zoner',
                   'K7GW',
                   'McAfee-GW-Edition',
                   'TrendMicro-HouseCall',
                   'Emsisoft',
                   'Ad-Aware']

CY_TRUSTED_AV = ["antiy_avl",
                 "avast",
                 "avg",
                 "avira",
                 "bitdefender",
                 "emsisoft",
                 "microworld_escan",
                 "eset_nod32",
                 "f_secure",
                 "fortinet",
                 "gdata",
                 "ikarus",
                 "kaspersky",
                 "malwarebytes",
                 "mcafee",
                 "mcafee_gw_edition",
                 "microsoft",
                 "nano_antivirus",
                 "panda",
                 "qihoo_360",
                 "sophos",
                 "superantispyware",
                 "symantec",
                 "tencent",
                 "totaldefense",
                 "trendmicro",
                  "virobot",
                  "alyac",
                  "ahnlab_v3",
                 "cat_quickheal",
                 "cyren",
                 "k7antivirus"]
TRUSTEDAV = ["f_secure",
             "microsoft",
             "eset_nod32",
             "avira",
             "symantec",
             "ikarus",
             "fortinet",
             "gdata",
             "bitdefender",
             "sophos",
             "mcafee",
             "trendmicro",
             "f_prot",
             "panda",
             "ahnlab_v3",
             "malwarebytes",
             "avast",
             "kaspersky",
             "vipre",
             "avg"
             ]

AVLIST = ['bkav',
          'microworld_escan',
          'nprotect',
          'cmc',
          'cat_quickheal',
          'alyac',
          'malwarebytes',
          'vipre',
          'k7antivirus',
          'alibaba',
          'k7gw',
          'thehacker',
          'agnitum',
          'f_prot',
          'symantec',
          'norman',
          'totaldefense',
          'trendmicro_housecall',
          'avast',
          'clamav',
          'kaspersky',
          'bitdefender',
          'nano_antivirus',
          'virobot',
          'aegislab',
          'tencent',
          'ad_aware',
          'emsisoft',
          'comodo',
          'f_secure',
          'drweb',
          'zillya',
          'trendmicro',
          'mcafee_gw_edition',
          'sophos',
          'cyren',
          'jiangmin',
          'avira',
          'antiy_avl',
          'kingsoft',
          'microsoft',
          'superantispyware',
          'ahnlab_v3',
          'gdata',
          'bytehero',
          'mcafee',
          'avware',
          'vba32',
          'panda',
          'zoner',
          'eset_nod32',
          'rising',
          'ikarus',
          'fortinet',
          'avg',
          'baidu_international',
          'qihoo_360'
          ]

MAPPING = {" loader": "trojdownloader",
           " risk": "riskware",
           "adw ": "adware",
           "adware": "adware",
           "backdoor": "backdoor",
           "banker": "trojan",
           "bkdr": "backdoor",
           "trj-spy": "trojspy",
           "nfostealer": "trojspy",
           "trojan-spy": "trojspy",
           "trojan.spy": "trojspy",
           "spy ": "trojspy",
           "spyware": "trojspy",
           "bundler": "adware",
           "dldr": "trojdownloader",
           "down ": "trojdownloader",
           "downware": "trojdownloader",
           "grayware": "riskware",
           " hack": "tool",
           "hackkms": "tool",
           "hacktool": "tool",
           "hktl": "tool",
           "keygen": "tool",
           "kms": "tool",
           "load ": "trojdownloader",
           "lock": "ransomware",
           "filecoder": "ransomware",
           "muldown": "trojdownloader",
           "ransom": "ransomware",
           "rkit": "rootkit",
           "expl": "exploit",
           "rogue": "riskware",
           "monitor": "tool",
           "risktool": "riskware",
           "rogueware": "riskware",
           "scareware": "riskware",
           "sys": "rootkit",
           "trj ": "trojan",
           "troj ": "trojan",
           "unwanted": "pua",
           "pe_": "virus",
           "virus": "virus",
           "pup": "pua",
           "pua": "pua",
           "optional": "pua",
           "not-a-virus": "pua",
           "potentially": "pua",
           "application": "pua", }

REPLACE = [" tool",
           "application",
           "backdoor",
           "based",
           "behaves",
           "downloader",
           "dropped",
           "dropper",
           "executor",
           "exploit",
           " gen ",
           "generic",
           "generik",
           "genome",
           "heur",
           "heuristic",
           "like",
           "malware",
           "obfuscated",
           "optional",
           "packed",
           "posible",
           "possible",
           "program",
           "ransomware",
           "reputation",
           "riskware",
           "rootkit",
           "suspect",
           "trojan",
           "unclassified",
           "unknown",
           "variant",
           "virus",
           "ware",
           "win32 ",
           "win64",
           "worm",
           "linux",
           "suspicious",
           "msil",
           "html",
           "script",
           "macos",
           "android",
           "java",
           "nsis",
           "troj",
           "other",
           "agent",
           "razy",
           "kazy",
           "zusy",
           "barys",
           "symmi"]

KNOWN_ADWARE_LIST = ['graftor',
                     'dapato',
                     'dialer',
                     'addrop',
                     'egguard',
                     'cashback',
                     'diamin',
                     'midie',
                     'loadmoney',
                     'downloadguid',
                     'advml',
                     'toptools',
                     'rukometa',
                     'eorezo',
                     'monetizer',
                     'multi',
                     'onescan',
                     'cloud',
                     'strictor',
                     'netfilter',
                     'yantai',
                     'browsefox',
                     'downloadadmin',
                     'somoto',
                     'ibryte',
                     'browsefox',
                     'amonetize',
                     'installmonster',
                     'bundlore',
                     'multiplug',
                     'installcore',
                     'opencandy',
                     'softpulse',
                     'mypcbackup',
                     'elex',
                     'icloader',
                     'wajam',
                     'mediamagnet',
                     'pennybee',
                     'bundleloader',
                     'gamevance',
                     'adsearcher',
                     'bundlore',
                     'pullupdate',
                     'multi',
                     'crossrider',
                     'mikey',
                     'installmonstr',
                     'dealply',
                     'shedun']

MS_FAMILY_GENERIC = ['skeeyah', 'tiggre', 'dynamer', 'dorv', 'occamy']

MS_FAMILY_BLACKLIST = ['AndroidOS/LockScreen!rfn']